---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "46"
year: "2024"
contributor: 
- Redaktion LIBREAS
title: "Editorial #46: Bestandserhaltung in Bibliotheken"
pdf: "main.pdf"
date: 2024-12-20
comments: false
sharing: true
footer: true

---