---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "46"
year: "2024"
contributor:
  - "Ulf Preuß"
title: "Digitaler Wandel in der Kultur – Bibliotheken und Förderung im Land Brandenburg"
abstract: "Die sich in immer kürzeren Zyklen verändernden digitalen Rahmenbedingungen bieten Kultureinrichtungen neue Chancen und stellen gleichzeitig große Herausforderungen für die damit verbundenen Anpassungsprozesse dar. Jede Kultureinrichtung hat dabei einen individuellen, konkreten Handlungsrahmen, in welchem die kulturelle Aufgabe realisiert wird, so auch die Bibliotheken. Im Land Brandenburg wurden kulturpolitische Rahmenbedingungen auf strategischer und konzeptioneller Ebene neu ausgerichtet. Mit einer neuen Förderlinie steht ein umfassendes Förderwerkzeug zur Verfügung. Für die Förderung von Digitalisierungsmaßnahmen spielen dabei institutionelle Digitalstrategien eine Schlüsselrolle. Der Beitrag ordnet die Richtlinie in diesem Kontext kurz ein."
pdf: "main.pdf"
date: 2024-12-22
comments: false
sharing: true
footer: true

---