---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "46"
year: "2024"
contributor: 
  - "Ellen Euler"
title: "VG WORT und Open Access: Ein Balanceakt für Wissenschaftler*innen"
abstract: "Der folgende Beitrag geht der Frage nach, wie sich die Teilnahme an Ausschüttungen durch die VG WORT mit den Prinzipien von Open Access und der Wissenschaftsethik in Einklang bringen lässt und beleuchtet das Spannungsverhältnis zwischen der Förderung des Gemeinwohls durch freien Zugang zu Wissen und der Wahrnehmung von gesetzlichen Vergütungsansprüchen, insbesondere im Kontext öffentlich finanzierter Wissenschaft."
pdf: "main.pdf"
date: 2024-12-21
comments: false
sharing: true
footer: true

---


