---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "46"
year: "2024"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #15 (Herbst-Winter 2024)"
pdf: "https://doi.org/10.18452/..."
doi: "10.18452/..."
date: 2024-12-22
comments: false
sharing: true
footer: true

---