---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "46"
year: "2024"
contributor: 
- "Ben Kaden"
title: "Kolumne Bibliotheksphilokartie: Eine Erinnerungskarte aus Berlin-Friedrichshain"
pdf: "https://doi.org/10.18452/31227"
doi: "10.18452/31227"
date: 2024-12-22
comments: false
sharing: true
footer: true

---