---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "46"
year: "2024"
contributor: 
- "Vorstand LIBREAS-Verein"
title: "In eigener Sache: Bericht über die Aktivitäten des LIBREAS-Vereins 2023/2024"
pdf: "https://doi.org/10.18452/31228"
doi: "10.18452/31228"
date: 2024-12-21
comments: false
sharing: true
footer: true
---